# Generated by Django 3.1.6 on 2021-03-10 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTitle', models.CharField(max_length=64)),
                ('commentDescription', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentListingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentListingId', to='auctions.listing')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
