# Generated by Django 3.1.6 on 2021-02-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
        ('auctions', '0002_category_listing'),
    ]

    operations = [
    ]
