# Generated by Django 3.1.6 on 2021-02-25 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='watched_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
