# Generated by Django 3.1.6 on 2021-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listingId',
            field=models.IntegerField(),
        ),
    ]
